### ISSUE TITLE
pub modifier causes error in Interface

### ISSUE THREAD

**Issue by exoego** [olivernybroe/Wing-Idea#10]
Thanks for creating this plugin.
I've found an issue.

- wing-idea: 0.1.1
- intellij idea: Build #IU-232.9921.47, built on September 13, 2023

error with `pub` | no error without `pub`
---|---
<img width="431" alt="image" src="https://github.com/olivernybroe/Wing-Idea/assets/127635/923548c3-78ff-4b82-933a-6ff6ba30486e"> | <img width="358" alt="image" src="https://github.com/olivernybroe/Wing-Idea/assets/127635/e599cfd8-634c-4e4c-9ef4-ac98ccb77901">

Since Wing compiler can compile `pub` signature in interface, Wing-Idea should allow that too.

This code: https://github.com/winglang/wing/blob/31c8698f56f4479e5199c2de76097ac40f04fd6c/examples/tests/valid/assertions.w#L6-L13

**Comment by olivernybroe** [comment]
Ah, looks like I had written it as `public` instead of `pub` in the language :) 
I'll change it, thanks for reporting!

**Comment by olivernybroe** [comment]
I have created a new version which I will release in a couple of days, but if you want the fix now, you can manually install the new version
[Wing-0.1.2.zip](https://github.com/olivernybroe/Wing-Idea/files/12845345/Wing-0.1.2.zip)


Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
